###########################################
#                                         #
#             SimpleCloud NPC             #
#              Configuration              #
#                  v1.0.0                 #
#                                         #
###########################################

general:




messages:
  prefix: